clastic_alias:
    resource: "@ClasticAliasBundle/Resources/config/backoffice_routing.xml"

clastic_menu:
    resource: "@ClasticMenuBundle/Resources/config/backoffice_routing.xml"

clastic_media:
    resource: "@ClasticMediaBundle/Resources/config/backoffice_routing.xml"

clastic_taxonomy:
    resource: "@ClasticTaxonomyBundle/Resources/config/backoffice_routing.xml"

clastic_block:
    resource: "@ClasticBlockBundle/Resources/config/backoffice_routing.xml"

clastic_backoffice:
    resource: "@ClasticBackofficeBundle/Resources/config/routing.xml"

clastic_contact_form:
    resource: "@ClasticContactFormBundle/Resources/config/backoffice_routing.xml"

clastic_contact_form_contact-form-data:
    resource: "@ClasticContactFormBundle/Resources/config/routing/contactformdata.xml"
    prefix:   /contact-form-data

clastic_contact_form_contact-form-type:
    resource: "@ClasticContactFormBundle/Resources/config/routing/contactformtype.xml"
    prefix:   /contact-form-type


