jwi_contact:
    resource: "@JwiContactBundle/Resources/config/routing.xml"
    prefix:   /

_clastic_admin:
    resource: routing_admin.yml
    prefix: admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_front:
    resource: "@ClasticFrontBundle/Resources/config/routing.xml"
    prefix:   /