<?php

namespace Clastic\ContactFormBundle\Entity;

/**
 * ContactFormDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactFormDataRepository extends \Doctrine\ORM\EntityRepository
{
}
