<?php

namespace Clastic\ContactFormBundle\Entity;

/**
 * ContactFormTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactFormTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
