<?php

namespace AppBundle\Entity;

/**
 * ContactDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactDataRepository extends \Doctrine\ORM\EntityRepository
{
}
